version: "3.8"

services:
    app:
        image: dockerpi
        working_dir: /app

    mysql:
        image: mysql:8.0
        volumes:
          - mysql-data/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: crypto

volumes:
  mysql-data: