version: "3.8"

services:

    mysqldb:
        image: mysql:8.0
        volumes:
          - mysql-data:/var/lib/mysql
          - ./data:/docker-entrypoint-initdb.d
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          - TZ=America/New_York
          - MYSQL_USER=PyU
          - MYSQL_PASSWORD=PyP
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_DATABASE=crypto
        networks:
          - local

    app:
      image: dockerpi
      working_dir: /app
      environment:
        - TZ=America/New_York
      depends_on:
        - mysqldb
      networks:
        - local

networks:
  local:
    driver: bridge
volumes:
  mysql-data: