version: "3.8"

services:
    app:
        image: dockerpi
        working_dir: /app

    mysqldb:
        image: mysql:8.0
        ports:
          - 33065:33065
        volumes:
          - mysql-data/:/var/lib/mysql
        environment:
          - MYSQL_USER=PyU
          - MYSQL_PASSWORD=Pyp
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_DATABASE=crypto

volumes:
  mysql-data: